<a href="https://colab.research.google.com/github/Samruddhi9657/python-workshop/blob/main/NUMPYBASIS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [ ]:


b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
c = np.array([[1,2],[3,4]])
print(c)

[[1 2]
 [3 4]]


In [ ]:
e = np.array([1,2,3,4],dtype=float)
e

array([1., 2., 3., 4.])

In [ ]:
  f = np.array([1,2,3,4],dtype=complex)
  f







array([1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j])

In [ ]:
y = np.arange(15,60,4)
y

array([15, 19, 23, 27, 31, 35, 39, 43, 47, 51, 55, 59])

In [ ]:
u = np.arange(12).reshape(2,2,3)
u

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [ ]:
np.ones([2,2,2])

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [ ]:
np.zeros([2,2,2])

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [ ]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [ ]:
np.random.random((3,4))

array([[0.30560479, 0.2369541 , 0.32853778, 0.18498343],
       [0.43084413, 0.41865699, 0.9047226 , 0.95644863],
       [0.2187106 , 0.1698014 , 0.8657627 , 0.33282544]])

In [ ]:
np.random.random((4,5))

array([[0.67062703, 0.56727639, 0.45344051, 0.38381806, 0.71669515],
       [0.96833471, 0.26679401, 0.00268262, 0.8197499 , 0.91688883],
       [0.37949507, 0.81709331, 0.48143998, 0.54541451, 0.37275141],
       [0.44931924, 0.71993793, 0.69953406, 0.0205962 , 0.03436696]])

In [ ]:
np.linspace(-10,10,50,dtype=float)

array([-10.        ,  -9.59183673,  -9.18367347,  -8.7755102 ,
        -8.36734694,  -7.95918367,  -7.55102041,  -7.14285714,
        -6.73469388,  -6.32653061,  -5.91836735,  -5.51020408,
        -5.10204082,  -4.69387755,  -4.28571429,  -3.87755102,
        -3.46938776,  -3.06122449,  -2.65306122,  -2.24489796,
        -1.83673469,  -1.42857143,  -1.02040816,  -0.6122449 ,
        -0.20408163,   0.20408163,   0.6122449 ,   1.02040816,
         1.42857143,   1.83673469,   2.24489796,   2.65306122,
         3.06122449,   3.46938776,   3.87755102,   4.28571429,
         4.69387755,   5.10204082,   5.51020408,   5.91836735,
         6.32653061,   6.73469388,   7.14285714,   7.55102041,
         7.95918367,   8.36734694,   8.7755102 ,   9.18367347,
         9.59183673,  10.        ])

In [ ]:

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
A8 = np.arange([1,2,3,4,5,6,7,8,9,10])
A8

TypeError: unsupported operand type(s) for -: 'list' and 'int'

In [ ]:
a1 = np.array([1,2,3,4,5,6,7,8,9,10])
a1.dtype

dtype('int64')

In [ ]:
Z = np.array([1,2,3,4,5])
Z+6

array([ 7,  8,  9, 10, 11])

In [ ]:
T = np.array([[1,2],[3,4]])
T**2

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
T1 = np.array([[1,2],[3,4]])
T2 = np.array([[5,6],[7,8]])
T1**T2

array([[    1,    64],
       [ 2187, 65536]])

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[75., 31., 60.],
       [32., 25., 51.],
       [64.,  6., 19.]])

In [ ]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)
a1

array([[ 1., 26., 69.],
       [ 2., 53.,  6.],
       [63.,  7., 90.]])

In [ ]:
a1

array([[ 1., 26., 69.],
       [ 2., 53.,  6.],
       [63.,  7., 90.]])

In [ ]:

a1
np.prod(a1,axis=0)

array([  126.,  9646., 37260.])

In [ ]:
A5 = np.array([[1,2],[3,4]])
A5
np.prod(A5,axis=0)

array([3, 8])

In [ ]:
A5 = np.array([[1,2],[3,4]])
A5
np.sum(A5,axis=0)

array([4, 6])

In [ ]:
np.ceil(np.random.random((2,3))*100)

array([[50., 11., 47.],
       [34., 65., 26.]])

In [ ]:
np.exp(a1)

array([[2.71828183e+00, 1.95729609e+11, 9.25378173e+29],
       [7.38905610e+00, 1.04137594e+23, 4.03428793e+02],
       [2.29378316e+27, 1.09663316e+03, 1.22040329e+39]])

In [ ]:
np.exp(A5)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [ ]:
a1[2:5:2]

array([[63.,  7., 90.]])

In [ ]:
T[0:2,1::2]

array([[2],
       [4]])

In [ ]:
a1


array([[ 1., 26., 69.],
       [ 2., 53.,  6.],
       [63.,  7., 90.]])

In [ ]:
a1[1,0]

np.float64(2.0)

In [ ]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [ ]:
a3[0,1,:]

array([3, 4, 5])

In [ ]:
a1

for i in a1:
  print(i)

[ 1. 26. 69.]
[ 2. 53.  6.]
[63.  7. 90.]


In [ ]:
for i in np.nditer(a1):
  print(i)

1.0
26.0
69.0
2.0
53.0
6.0
63.0
7.0
90.0


In [ ]:
np.transpose(a1)
a1.T

array([[ 1.,  2., 63.],
       [26., 53.,  7.],
       [69.,  6., 90.]])

In [ ]:
a1.ravel()

array([ 1., 26., 69.,  2., 53.,  6., 63.,  7., 90.])